### PR TITLE
still need some fixing...

### PR DESCRIPTION
**Pull request by Ekamba**

### CODE REVIEW

**Comment by senner007** [comment]
Hi :)
I see a lot of good stuff here. Also a lot that we haven't talked about in class
It's great to be inspired by others, but also make sure you unserstand everything yourself.
There are just a few issues, such as when you type really fast, the search doesn't keep up as we talked about in the main thread. 
Otherwise, keep up the good work 👍

**Comment by Ekamba** [comment]
Hi Niels, Thank you for your review. As you can See My app has a problem with the loader that keeps loading when I clean up the search bar. Can you help with that? thank you a lot.

**Comment by senner007** [comment]
Yes. It can be fixed by replacing the searchUsers function in GithubState.js to this instead:

```
  const searchUsers = async text => {
    setLoading();

    var payload;
    try {
      const res = await axios.get(
        `https://api.github.com/search/users?q=${text}&client_id=${githubClientId}&client_secret=${githubClientSecret}`
      );
      payload = res.data.items;
    } catch (err) {
      payload = [];
    }

    dispatch({
      type: SEARCH_USERS,
      payload: payload
    });
  };
```

**Comment by senner007** [comment]
You also have a few criticical security issues that needs fixing. This can be done with "npm audit fix"
As mentioned, I recommend that you try to write this logic by yourself from the ground up. Then compare with at someone else's code afterwards

**Comment by Ekamba** [comment]
Hi Niels, sorry for this delay. Actually when I just my code as you suggest my application crash when I am tapping in the search bar and the error is that "TypeError: Cannot read property 'length' of undefined" . And I change the users to user, this no record after tapping in the search bar. I do not know what is wrong.

**Pull request merged**
